#!/usr/bin/env bash
set -euo pipefail

# ironclaw.sh — Install and configure IronClaw
#
# IronClaw is a pre-built Rust binary with WASM sandbox (Wasmtime embedded).
# Uses libsql by default (zero-config, no PostgreSQL required).
# PostgreSQL + pgvector is optional for production scale.
#
# Config: ~/.ironclaw/.env (bootstrap) + database settings table
# Optional: ~/.ironclaw/config.toml (overrides DB settings)
#
# Onboard is fully skipped — it requires interactive stdin/browser.
# All config is done via env vars in ~/.ironclaw/.env.
#
# Usage: Run as the IronClaw user (e.g., izzy). Not root.

BIN_DIR="${HOME}/bin"
CARGO_BIN="${HOME}/.cargo/bin"
IRONCLAW_DIR="${HOME}/.ironclaw"
IRONCLAW_ENV="${IRONCLAW_DIR}/.env"
USER_ENV="${HOME}/.env"

# ── Helpers ──────────────────────────────────────────────────────────────────

info()  { printf '\033[1;34m[INFO]\033[0m  %s\n' "$1"; }
ok()    { printf '\033[1;32m[OK]\033[0m    %s\n' "$1"; }
warn()  { printf '\033[1;33m[WARN]\033[0m  %s\n' "$1"; }
fatal() { printf '\033[1;31m[FAIL]\033[0m  %s\n' "$1" >&2; exit 1; }

# ── Download pre-built binary ────────────────────────────────────────────────

install_binary() {
    info "Installing IronClaw binary..."

    mkdir -p "${BIN_DIR}"

    # Check if already installed
    if [[ -x "${BIN_DIR}/ironclaw" ]] || [[ -x "${CARGO_BIN}/ironclaw" ]]; then
        local existing="${BIN_DIR}/ironclaw"
        [[ -x "$existing" ]] || existing="${CARGO_BIN}/ironclaw"
        local ver
        ver="$("$existing" --version 2>/dev/null || echo 'unknown')"
        ok "IronClaw already installed: ${ver}"
        ensure_symlink "$existing"
        return 0
    fi

    # Official installer (puts binary in ~/.cargo/bin/)
    local installer_url="https://github.com/nearai/ironclaw/releases/latest/download/ironclaw-installer.sh"
    info "Running official installer..."
    if curl --proto '=https' --tlsv1.2 -LsSf "$installer_url" | sh 2>&1; then
        if [[ -x "${CARGO_BIN}/ironclaw" ]]; then
            ensure_symlink "${CARGO_BIN}/ironclaw"
            local ver
            ver="$("${BIN_DIR}/ironclaw" --version 2>/dev/null || echo 'unknown')"
            ok "IronClaw installed: ${ver}"
            return 0
        fi
    fi

    # Check if it landed somewhere else
    local found
    found="$(command -v ironclaw 2>/dev/null || true)"
    if [[ -n "$found" ]]; then
        ensure_symlink "$found"
        ok "IronClaw found at: ${found}"
        return 0
    fi

    fatal "Could not install IronClaw binary"
}

ensure_symlink() {
    local source="$1"
    if [[ "$source" != "${BIN_DIR}/ironclaw" ]]; then
        ln -sf "$source" "${BIN_DIR}/ironclaw"
        ok "Symlinked ${source} → ${BIN_DIR}/ironclaw"
    fi
}

# ── Configure ────────────────────────────────────────────────────────────────

configure() {
    info "Configuring IronClaw..."

    mkdir -p "${IRONCLAW_DIR}"
    mkdir -p "${IRONCLAW_DIR}/channels"
    mkdir -p "${IRONCLAW_DIR}/tools"

    # Source user env for secrets
    if [[ -f "${USER_ENV}" ]]; then
        set -a; source "${USER_ENV}"; set +a
    fi

    # Write IronClaw's own .env (bootstrap config)
    write_ironclaw_env

    # Skip interactive onboard entirely — it requires stdin/browser.
    # All config is handled via env vars in ~/.ironclaw/.env.
    if [[ -z "${ANTHROPIC_API_KEY:-}" ]] && [[ -z "${OPENROUTER_API_KEY:-}" ]]; then
        warn "No LLM API key in ~/.env — set ANTHROPIC_API_KEY or OPENROUTER_API_KEY before starting"
    else
        ok "LLM credentials found in environment"
    fi
}

write_ironclaw_env() {
    # Source user env for secrets
    if [[ -f "${USER_ENV}" ]]; then
        set -a; source "${USER_ENV}"; set +a
    fi

    # Determine LLM backend
    local llm_backend="anthropic"
    local llm_api_key="${ANTHROPIC_API_KEY:-}"

    if [[ -z "$llm_api_key" ]] && [[ -n "${OPENROUTER_API_KEY:-}" ]]; then
        llm_backend="openai_compatible"
        llm_api_key="${OPENROUTER_API_KEY}"
    fi

    cat > "${IRONCLAW_ENV}" <<ENV
# IronClaw bootstrap configuration
# Generated by setup on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# This file is loaded BEFORE database connection.
# Priority: env var > TOML config > DB settings > defaults

# Database — libsql is zero-config (no PostgreSQL needed)
DATABASE_BACKEND=libsql
LIBSQL_PATH=${IRONCLAW_DIR}/ironclaw.db

# LLM provider
LLM_BACKEND=${llm_backend}
$(if [[ "$llm_backend" == "anthropic" ]]; then
    echo "ANTHROPIC_API_KEY=${llm_api_key:-REPLACE_ME}"
elif [[ "$llm_backend" == "openai_compatible" ]]; then
    echo "LLM_BASE_URL=https://openrouter.ai/api/v1"
    echo "LLM_API_KEY=${llm_api_key:-REPLACE_ME}"
    echo "LLM_MODEL=anthropic/claude-sonnet-4-6"
fi)

# Mark onboard as completed (skip auto-trigger on first run)
ONBOARD_COMPLETED=true

# Headless mode — disable interactive CLI/TUI (prevents stdin auth prompts)
CLI_ENABLED=false

# WASM sandbox
WASM_ENABLED=true
WASM_DEFAULT_TIMEOUT_SECS=60
WASM_DEFAULT_MEMORY_LIMIT=10485760

# Docker sandbox (optional, for heavier workloads)
SANDBOX_ENABLED=true
SANDBOX_POLICY=readonly
SANDBOX_TIMEOUT_SECS=120
SANDBOX_MEMORY_LIMIT_MB=2048

# Telegram (if configured)
$(if [[ -n "${TELEGRAM_BOT_TOKEN:-}" ]]; then
    echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}"
fi)
ENV

    chmod 600 "${IRONCLAW_ENV}"
    ok "IronClaw env written to ${IRONCLAW_ENV}"
}

# ── Systemd service ─────────────────────────────────────────────────────────

install_service() {
    local ironclaw="${BIN_DIR}/ironclaw"

    # Try built-in service installer
    info "Installing systemd service..."
    if "$ironclaw" service install 2>/dev/null; then
        ok "Systemd service installed via 'ironclaw service install'"
        return 0
    fi

    # Fallback: write unit file manually
    warn "Built-in service install failed — writing unit file manually"
    local svc_dir="${HOME}/.config/systemd/user"
    mkdir -p "$svc_dir"

    # Build PATH that includes both ~/bin and ~/.cargo/bin
    local svc_path="${BIN_DIR}:${CARGO_BIN}:${HOME}/.local/bin:/usr/local/bin:/usr/bin:/bin"

    cat > "${svc_dir}/ironclaw.service" <<EOF
[Unit]
Description=IronClaw AI Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${BIN_DIR}/ironclaw run --no-onboard
Restart=on-failure
RestartSec=10
EnvironmentFile=%h/.env
EnvironmentFile=%h/.ironclaw/.env
Environment=PATH=${svc_path}
Environment=IRONCLAW_BASE_DIR=%h/.ironclaw
Environment=CLI_ENABLED=false

[Install]
WantedBy=default.target
EOF

    systemctl --user daemon-reload 2>/dev/null || true
    ok "Systemd service installed (manual)"
}

# ── Health check ─────────────────────────────────────────────────────────────

verify() {
    info "Running verification..."
    local ironclaw="${BIN_DIR}/ironclaw"

    # Binary runs
    if "$ironclaw" --version &>/dev/null; then
        ok "Binary: $("$ironclaw" --version 2>/dev/null)"
    else
        fatal "Binary does not execute"
    fi

    # Config exists
    if [[ -f "${IRONCLAW_ENV}" ]]; then
        ok "Config: ${IRONCLAW_ENV}"
    else
        warn "Config not found at ${IRONCLAW_ENV}"
    fi

    # Directory structure
    for dir in "${IRONCLAW_DIR}/channels" "${IRONCLAW_DIR}/tools"; do
        if [[ -d "$dir" ]]; then
            ok "Directory: ${dir}"
        fi
    done

    # Docker (optional, for shell sandbox)
    if command -v docker &>/dev/null && docker info &>/dev/null; then
        ok "Docker available (shell sandbox ready)"
    else
        warn "Docker not available — WASM tools work, but shell sandbox won't"
    fi

    # Service file
    if [[ -f "${HOME}/.config/systemd/user/ironclaw.service" ]]; then
        ok "Systemd service file present"
    else
        warn "No systemd service file found"
    fi
}

# ── Main ─────────────────────────────────────────────────────────────────────

main() {
    echo ""
    info "Setting up IronClaw for user: $(whoami)"
    echo ""

    install_binary
    configure
    install_service
    verify

    local user
    user="$(whoami)"

    echo ""
    echo "════════════════════════════════════════════════════"
    echo "  IronClaw — SETUP COMPLETE"
    echo "════════════════════════════════════════════════════"
    echo ""

    local has_keys=false
    if [[ -n "${ANTHROPIC_API_KEY:-}" ]] || [[ -n "${OPENROUTER_API_KEY:-}" ]]; then
        has_keys=true
    fi

    if $has_keys; then
        echo "  Using libsql (zero-config, no PostgreSQL needed)."
        echo ""
        echo "  Ready to start!"
    else
        echo "  Set LLM credentials in ~/.env:"
        echo "    ANTHROPIC_API_KEY=sk-ant-...     # for Anthropic direct"
        echo "    # OR"
        echo "    OPENROUTER_API_KEY=sk-or-...     # for OpenRouter"
        echo ""
        echo "  Telegram (optional):"
        echo "    TELEGRAM_BOT_TOKEN=<from @BotFather>"
    fi
    echo ""
    echo "  Optional: run interactive onboard for full setup"
    echo "    sudo -u ${user} -i"
    echo "    ironclaw onboard --quick"
    echo ""
    echo "  Start:   systemctl --user enable --now ironclaw"
    echo "  Logs:    journalctl --user -u ironclaw -f"
    echo "  Status:  ironclaw status"
    echo "  Doctor:  ironclaw doctor"
    echo ""
    echo "  Database: libsql at ~/.ironclaw/ironclaw.db"
    echo "  To upgrade to PostgreSQL later:"
    echo "    Set DATABASE_BACKEND=postgres + DATABASE_URL in ~/.ironclaw/.env"
    echo ""
}

main "$@"
